---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(lubridate)
library(rvest)
library(dplyr)
```

```{r}
url <- "https://opendata.city-adm.lviv.ua/datastore/dump/e406ed26-f910-4702-ad7e-6fd4777160ac?bom=True"
streetlight <- read.csv(url(url), encoding = "UTF-8")
streetlight
```

```{r}
streetlight <- streetlight %>%
  select (IndicatorName, IndicatorValue, IndicatorValueYear)

streetlight
```

```{r}
streetlight <- streetlight %>%
  filter(IndicatorName == "Загальна протяжність мереж зовнішнього освітлення (освітлення вулиць, внутрішніх дворів тощо) ")
streetlight
```

```{r}
url <- "https://opendata.city-adm.lviv.ua/datastore/dump/47b6d340-110a-4a22-b934-47f840b7e8fe?bom=True"
grabegi <- read.csv(url(url), encoding = "UTF-8")
grabegi
```

```{r}
grabegi <- grabegi %>%
  select (IndicatorName, IndicatorValue, IndicatorValueYear)

grabegi
```
```{r}
grabegi <- grabegi %>%
  filter(IndicatorName == "Випадки хуліганства")
grabegi
```

```{r}
streetlight_grabegi <- merge(streetlight, grabegi, all=TRUE) %>%
  arrange(IndicatorValueYear) %>%
  mutate(IndicatorValue = as.character(IndicatorValue) %>% as.numeric()) 
```

```{r}
write.csv(streetlight_grabegi, "streetlight_grabegi.csv", row.names = FALSE)
```

```{r}
read.csv("streetlight_grabegi.csv")
```

```{r}
library(ggplot2)
library(dplyr)

ggplot(streetlight_grabegi, aes(IndicatorValueYear, IndicatorValue)) +
  geom_line(size=1, alpha=0.4) +
  geom_point() +
  scale_y_continuous (name = "Кількість") +
  scale_x_continuous(name = "Рік", breaks = 2010:2019) +
  theme_minimal() +
  facet_wrap(vars(IndicatorName))

ggsave("2.png")
```





