---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(lubridate)
library(rvest)
library(dplyr)
```

```{r}
url <- "https://opendata.city-adm.lviv.ua/datastore/dump/4cdc01e3-2ae8-4c3a-8667-d77571f5fcb8?bom=True"
streetlight <- read.csv(url(url), encoding = "UTF-8")
streetlight
```

```{r}
streetlight <- streetlight %>%
  select (IndicatorName, IndicatorValue, IndicatorValueYear)

streetlight
```

```{r}
streetlight <- streetlight %>%
  filter(IndicatorName == "Вуличне освітлення")
streetlight
```

```{r}
url <- "https://opendata.city-adm.lviv.ua/datastore/dump/47b6d340-110a-4a22-b934-47f840b7e8fe?bom=True"
grabegi <- read.csv(url(url), encoding = "UTF-8")
grabegi
```

```{r}
grabegi <- grabegi %>%
  select (IndicatorName, IndicatorValue, IndicatorValueYear)

grabegi
```
```{r}
grabegi <- grabegi %>%
  filter(IndicatorName == "Випадки хуліганства")
grabegi
```

```{r}
streetlight_grabegi <- merge(streetlight, grabegi, all=TRUE) %>%
  arrange(IndicatorValueYear)
```

```{r}
write.csv(streetlight_grabegi, "streetlight_grabegi.csv", row.names = FALSE)
```

```{r}
read.csv("streetlight_grabegi.csv")
```

```{r}
chart <- read_csv("streetlight_grabegi.csv")
ggplot(chart, aes(IndicatorValueYear, IndicatorValue, IndicatorName)) +
scale_x_continuous(name = "Рік", breaks = 2010:2019) +
  geom_line(aes(color = IndicatorName))  
```
